# Tutorial 2
Acceso dentro del contenido del arreglo de datos

## Primer paso, cargar datos en nuestro arreglo.

Revisar tutorial anterior, usaremos la misma base.

In [ ]:
# importamos librerías
import pandas as pd
# definimos la localización de la base de datos
path = '/content/base_tut_1.xlsx'
df = pd.read_excel(path)
# ver primeras 5 filas
df.head()

   id  edad sexo   peso  talla    TAS   TAD HAS DM2
0   1  28.0    F  113.5   1.54  142.0  79.0  NO  SI
1   2  46.0    M  122.5   1.76  117.0  74.0  SI  NO
2   3  54.0    F  120.0   1.50  140.0  70.0  SI  SI
3   4  38.0    F  102.0   1.60  110.0  70.0  NO  NO
4   5  40.0    F  118.0   1.78  114.0  80.0  NO  SI

## Acceso a variables (columnas)
Hay dos formas de acceder a las variables del arreglo de datos. Una es con punto y el nombre de la variable y la otra es con la notación de diccionario

### Punto y nombre (atributo)
En python, los atributos son propiedades de los objetos a los que podemos acceder con punto pero sin paréntes (no son funciones que se ejecutan).

`df.peso`

Esta notación solo funciona cuando la variable tiene un nombre válido en python. En este arreglo de datos todas las variable pueden ser accesadas así.

Esta notación tiene limitantes (ver tutorial 1).

In [ ]:
df.HAS.head()

0    NO
1    SI
2    SI
3    NO
4    NO
Name: HAS, dtype: object

In [ ]:
df.peso

0     113.5
1     122.5
2     120.0
3     102.0
4     118.0
      ...
80     91.0
81    142.0
82    128.0
83    142.0
84    110.0
Name: peso, Length: 85, dtype: float64

### Notación de diccionario

En un diccionario definido como:
```python
diccionario = {'a': 1, 'b': 2}
```

podemos acceder a las "llaves" con corchetes:

```python
diccionario['a'] == 1 # True
```

En pandas, podemos acceder a las columnas de la misma manera:

In [ ]:
df['peso'].head()

0    113.5
1    122.5
2    120.0
3    102.0
4    118.0
Name: peso, dtype: float64

## Serie de datos
Las columnas de nuestro arreglo son series de datos que pueden almacenarse diréctamente en variables:

In [ ]:
peso = df['peso']
peso.head()

0    113.5
1    122.5
2    120.0
3    102.0
4    118.0
Name: peso, dtype: float64

## Operaciones aritméticas a nivel de serie

Es posible realizar operaciones matemáticas con toda la sere de datos, por ejemplo:

In [ ]:
df['edad']

0     28.0
1     46.0
2     54.0
3     38.0
4     40.0
      ...
80    40.0
81    43.0
82    42.0
83    50.0
84    31.0
Name: edad, Length: 85, dtype: float64

In [ ]:
df['edad']*2

0      56.0
1      92.0
2     108.0
3      76.0
4      80.0
      ...
80     80.0
81     86.0
82     84.0
83    100.0
84     62.0
Name: edad, Length: 85, dtype: float64

Al multiplicar por 2 se aplicó la multiplicación a todos los datos de la serie

## Operaciones entre series
Realizar operaciones aritméticas entre series es tribial.

Multipliquemos el número de id por el peso:

In [ ]:
df['peso'] * df['id']

0       113.5
1       245.0
2       360.0
3       408.0
4       590.0
       ...
80     7371.0
81    11644.0
82    10624.0
83    11928.0
84     9350.0
Length: 85, dtype: float64

## Ejercicio 1

Calcula el índice de masa corporal de los pacientes:
Recuérda que la fórmula es:

$IMC = \frac{peso}{talla²}$

```python
# Multiplicación:
a * b

# División:
a / b

# Potencia
a ** 2 # cuadrado
b ** 3 # cubo
```

In [ ]:

imc = # tu código aquí
imc

## Guardar nuevas series en el arreglo de datos

Podemos guardar nuestra serie de `imc` fácilmente en el arreglo de datos como si fuera un diccionario

In [ ]:
df['imc'] = imc
df.head()

   id  edad sexo   peso  talla    TAS   TAD HAS DM2        imc
0   1  28.0    F  113.5   1.54  142.0  79.0  NO  SI  47.857986
1   2  46.0    M  122.5   1.76  117.0  74.0  SI  NO  39.546746
2   3  54.0    F  120.0   1.50  140.0  70.0  SI  SI  53.333333
3   4  38.0    F  102.0   1.60  110.0  70.0  NO  NO  39.843750
4   5  40.0    F  118.0   1.78  114.0  80.0  NO  SI  37.242772

## Operaciones lógicas

Es frecuente que necesitemos hacer operaciones lógicas con nuestros datos. Por ejemplo, quizá querramos saber cuántos de los pacientes tenían obesidad con IMC arriba de 35.

In [ ]:
morb = df['imc'] >= 35
morb.value_counts()

imc
True     74
False    11
Name: count, dtype: int64

In [ ]:
morb.mean()

0.8705882352941177

El 87% de los pacientes tuvieron un IMC arriba de 35!

## Filtrado con condicionales
Cuando tenermos una serie de datos que tiene como valores `True` y `False` podemos filtrar nuestros datos para los que sean Verdaderos.

Supongamos que queremos conocer las características de los pacientes con obesidad mórbida.

In [ ]:
df[morb].describe().T

,count,mean,std,min,25%,50%,75%,max
id,74.0,45.405405,24.497089,1.000000,25.250000,47.500000,65.750000,85.000000
edad,74.0,44.608108,8.549321,20.000000,40.000000,45.000000,50.000000,64.000000
peso,74.0,125.181081,23.744085,80.500000,111.000000,117.100000,133.925000,195.000000
talla,74.0,1.622162,0.095290,1.430000,1.560000,1.620000,1.670000,1.930000
TAS,73.0,131.657534,16.705970,100.000000,118.000000,133.000000,141.000000,184.000000
TAD,73.0,76.287671,10.463534,52.000000,70.000000,77.000000,83.000000,104.000000
imc,74.0,47.611476,8.579800,36.515714,42.185262,45.007476,51.349857,86.752849

## Ejercicio 2
Encuentra las características de los pacientes sin obesidad mórbida